<?php
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tanzania Spatial Studio</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
:root{--ink:#10251f;--muted:#63726c;--sand:#f4efe5;--paper:#fffdf8;--gold:#c59a45;--line:#d9d3c7;--accent:#176b55}
*{box-sizing:border-box}body{margin:0;background:var(--sand);color:var(--ink);font-family:Inter,system-ui,sans-serif}.top{padding:26px 4vw 18px;background:var(--ink);color:#fff}.top small{letter-spacing:.18em;text-transform:uppercase;color:#d9c58e}.top h1{font-size:clamp(30px,4vw,56px);margin:8px 0 5px;font-weight:800}.top p{margin:0;color:#cbd5d0}.studio{max-width:1450px;margin:auto;padding:28px 4vw 60px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:18px}.toolbar button,.toolbar select{border:1px solid var(--line);background:#fff;padding:11px 15px;border-radius:10px;font-weight:700}.toolbar button.active{background:var(--ink);color:#fff}.layout{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:20px}.canvas{background:var(--paper);border:1px solid var(--line);border-radius:18px;padding:20px;min-height:690px;overflow:auto}.plan-wrap{min-width:720px;display:flex;justify-content:center;padding:28px}.plan{position:relative;width:720px;height:560px;background:#f7f2e8;border:5px solid #263c34;box-shadow:0 14px 35px #00000014}.room{position:absolute;background:#fffdf8;border:2px solid #263c34;display:flex;align-items:center;justify-content:center;text-align:center;cursor:pointer;transition:.18s}.room:hover,.room.selected{background:#e8f1ed;box-shadow:inset 0 0 0 4px #c9dfd6}.room strong{display:block;font-size:18px}.room span{display:block;font-size:12px;color:var(--muted);margin-top:5px}.bed{position:absolute;background:#e5d7bd;border:2px solid #92784b;border-radius:7px;display:flex;align-items:center;justify-content:center;font-size:12px}.door{position:absolute;background:var(--paper);z-index:4}.window{position:absolute;background:#8db4c0;z-index:3}.furn{position:absolute;border:1px solid #8d8170;background:#eee4d1;border-radius:4px;font-size:10px;display:flex;align-items:center;justify-content:center}.side{background:var(--paper);border:1px solid var(--line);border-radius:18px;padding:20px;height:max-content}.side h3{margin-top:0}.stat{display:flex;justify-content:space-between;border-bottom:1px solid var(--line);padding:11px 0}.hint{font-size:13px;color:var(--muted);line-height:1.5}.mode{margin-top:20px}.house5 .r1{left:0;top:0;width:48%;height:38%}.house5 .r2{right:0;top:0;width:48%;height:38%}.house5 .r3{left:0;top:39%;width:38%;height:61%}.house5 .r4{left:40%;top:39%;width:60%;height:29%}.house5 .r5{left:40%;bottom:0;width:60%;height:30%}.single .r1{left:5%;top:5%;width:90%;height:90%}.single .r2,.single .r3,.single .r4,.single .r5{display:none}.suite .r1{left:0;top:0;width:64%;height:100%}.suite .r2{right:0;top:0;width:36%;height:55%}.suite .r3{right:0;bottom:0;width:36%;height:45%}.legend{display:flex;gap:14px;flex-wrap:wrap;font-size:12px;color:var(--muted);margin-top:10px}.legend i{display:inline-block;width:15px;height:9px;border:1px solid #555;margin-right:5px}.bedx{background:#e5d7bd}.winx{background:#8db4c0}.doorx{background:#fff;border:1px solid #333!important}
@media(max-width:900px){.layout{grid-template-columns:1fr}.side{order:-1}.canvas{min-height:600px}}
</style></head>
<body>
<header class="top"><small>Tanzania Hospitality Platform · Spatial Studio</small><h1>Don't just book a room. Understand the space.</h1><p>Interactive room and property layouts — from one room to a complete five-room house.</p></header>
<main class="studio">
<div class="toolbar"><select id="mode"><option value="single">Single Room</option><option value="suite">Hotel Suite</option><option value="house5">Five-Room House</option></select><button id="zoomOut">−</button><button id="zoomIn">+</button><button id="reset">Reset</button><span class="ms-auto small text-secondary" id="scale">100%</span></div>
<div class="layout"><section class="canvas"><div class="plan-wrap" id="wrap"><div class="plan single" id="plan">
<div class="room r1" data-name="Main room"><div><strong id="r1name">Single Room</strong><span>4.2 m × 5.0 m · 21 m²</span></div></div>
<div class="room r2" data-name="Bedroom 2"><div><strong>Bedroom 2</strong><span>3.8 m × 4.0 m</span></div></div>
<div class="room r3" data-name="Living room"><div><strong>Living Room</strong><span>5.0 m × 4.6 m</span></div></div>
<div class="room r4" data-name="Kitchen + dining"><div><strong>Kitchen + Dining</strong><span>4.2 m × 3.6 m</span></div></div>
<div class="room r5" data-name="Bedroom 3"><div><strong>Bedroom 3</strong><span>3.8 m × 4.0 m</span></div></div>
<div class="bed" style="left:24%;top:24%;width:32%;height:20%">BED</div><div class="furn" style="left:65%;top:28%;width:16%;height:10%">WARDROBE</div><div class="furn" style="left:65%;top:48%;width:16%;height:9%">DESK</div><div class="door" style="right:-5px;top:70px;width:9px;height:65px"></div><div class="window" style="left:25%;top:-5px;width:180px;height:7px"></div>
</div></div><div class="legend"><span><i class="bedx"></i>Furniture</span><span><i class="winx"></i>Window</span><span><i class="doorx"></i>Door opening</span><span>Click a room to inspect it</span></div></section>
<aside class="side"><h3 id="selected">Single Room</h3><p class="hint" id="desc">A real room is a relationship between furniture, circulation, openings and usable floor area.</p><div class="stat"><span>Floor area</span><strong id="area">21 m²</strong></div><div class="stat"><span>Width</span><strong id="width">4.2 m</strong></div><div class="stat"><span>Length</span><strong id="length">5.0 m</strong></div><div class="stat"><span>Zones</span><strong id="zones">4</strong></div><div class="mode"><strong>What this becomes</strong><p class="hint">This spatial engine is designed to grow into hotel room inventory, house planning, furniture placement, room status and eventually real floor-plan data.</p></div></aside>
</div></main>
<script>
const plan=document.querySelector('#plan'), mode=document.querySelector('#mode'), scale=document.querySelector('#scale');let zoom=1;
function setMode(v){plan.className='plan '+v;document.querySelectorAll('.room').forEach(x=>x.classList.remove('selected'));let title=v==='single'?'Single Room':v==='suite'?'Hotel Suite':'Five-Room House';document.querySelector('#selected').textContent=title;document.querySelector('#area').textContent=v==='single'?'21 m²':v==='suite'?'38 m²':'142 m²';document.querySelector('#width').textContent=v==='single'?'4.2 m':v==='suite'?'6.8 m':'12.0 m';document.querySelector('#length').textContent=v==='single'?'5.0 m':v==='suite'?'7.4 m':'14.0 m';document.querySelector('#zones').textContent=v==='single'?'4':v==='suite'?'6':'10';document.querySelector('#r1name').textContent=v==='single'?'Single Room':'Main Bedroom';document.querySelector('.bed').style.display=v==='single'?'flex':'none';document.querySelectorAll('.furn,.door,.window').forEach(e=>e.style.display=v==='single'?'':'none')}
mode.addEventListener('change',e=>setMode(e.target.value));document.querySelectorAll('.room').forEach(r=>r.addEventListener('click',()=>{document.querySelectorAll('.room').forEach(x=>x.classList.remove('selected'));r.classList.add('selected');document.querySelector('#selected').textContent=r.dataset.name;document.querySelector('#desc').textContent='Selected space: '+r.dataset.name+'. In the full system this selection will expose its dimensions, furniture, occupancy, room status and connected spaces.'}));
document.querySelector('#zoomIn').onclick=()=>{zoom=Math.min(1.6,zoom+.1);plan.style.transform='scale('+zoom+')';scale.textContent=Math.round(zoom*100)+'%'};document.querySelector('#zoomOut').onclick=()=>{zoom=Math.max(.7,zoom-.1);plan.style.transform='scale('+zoom+')';scale.textContent=Math.round(zoom*100)+'%'};document.querySelector('#reset').onclick=()=>{zoom=1;plan.style.transform='scale(1)';scale.textContent='100%';setMode(mode.value)};
</script></body></html>
